services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog_container
    restart: always
    ports:
      - "1025:1025"
      - "8025:8025"

  app:
    build:
      dockerfile: Dockerfile
    container_name: app_container
    restart: always
    env_file:
      - .env
    environment: #Database host is using local database present in local machine
      DATABASE_HOST: host.docker.internal #In order to use docker database use the name of database service, in my case it is postgres as written above
    volumes:
      - .:/app
    ports:
      - "3001:3001"
    depends_on:
      - postgres

volumes:
  postgres_data:
    driver: local
