/* Replace with your SQL commands */
DROP TABLE IF EXISTS public.users;
DROP TABLE IF EXISTS public.users_friends;
DROP TABLE IF EXISTS public.soft_skills;
DROP TABLE IF EXISTS public.users_soft_skills;
DROP TABLE IF EXISTS public.users_verification_tokens;
DROP INDEX IF EXISTS public."IDX_488c35bac4fae1d53ac47eb68b";
DROP TABLE IF EXISTS public.user_socials;
DROP TABLE IF EXISTS public.user_progress;
DROP TABLE IF EXISTS public.user_profiles;
DROP TABLE IF EXISTS public.user_notification_groups;
DROP TABLE IF EXISTS public.user_game_progress;
DROP TABLE IF EXISTS public.session;
DROP INDEX IF EXISTS public."IDX_session_expire";
DROP TABLE IF EXISTS public.notifications;
DROP TABLE IF EXISTS public.notification_types;
DROP TABLE IF EXISTS public.files;
DROP INDEX IF EXISTS public."IDX_332d10755187ac3c580e21fbc0";
DROP DATABASE IF EXISTS saas;